# Generated by Django 4.2.11 on 2024-05-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0005_delete_promotions_alter_categories_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'db_table': 'Promotions',
            },
        ),
        migrations.CreateModel(
            name='PromotionTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_need_min_price', models.BooleanField(default=False, verbose_name='Нужна ли минимальная сумма в заказе')),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Минимальная сумма в заказе для добавления акции')),
            ],
            options={
                'verbose_name': 'Условие акции',
                'verbose_name_plural': 'Условия акции',
                'db_table': 'PromotionTerms',
            },
        ),
        migrations.CreateModel(
            name='PromotionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Акционный продукт')),
                ('promotion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='promotions.promotion', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Акционный товар',
                'verbose_name_plural': 'Товары для акций',
                'db_table': 'PromotionProducts',
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promotions.promotionterms', verbose_name='Условия акции'),
        ),
    ]
