# Generated by Django 4.2.11 on 2024-05-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Carts',
        ),
    ]
