# Generated by Django 4.2.11 on 2024-04-29 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True, verbose_name='Заголовок отзыва')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Текст отзыва')),
                ('answer', models.CharField(max_length=200, null=True, verbose_name='Текст ответа на отзыв')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Замечательно')], verbose_name='Оценка от пользователя')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации отзыва')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'feedback',
                'ordering': ('id',),
            },
        ),
    ]
