# Generated by Django 4.2.11 on 2024-04-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='answer',
            field=models.TextField(max_length=200, null=True, verbose_name='Текст ответа на отзыв'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(max_length=200, null=True, verbose_name='Текст отзыва'),
        ),
    ]
