# Generated by Django 4.2.11 on 2024-05-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_promotions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotions',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='products',
            table='Products',
        ),
    ]
