# Generated by Django 4.2.11 on 2024-04-15 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_status_remove_order_status_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.status', verbose_name='Статус заказа'),
        ),
    ]
