# Generated by Django 4.2.11 on 2024-04-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='OrderStatus',
        ),
    ]
