# Generated by Django 4.2.11 on 2024-05-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_status_orderstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='Order_items',
        ),
    ]
